### ISSUE TITLE
UNLESS with old-style php_templates tags - parse errors

### ISSUE THREAD

**Issue by alexeyrybak** [alexeyrybak/blitz#17]
$ php -r '$B = new Blitz(); $B->load("{{ IF AAA }}AAA{{ END }}");'
$ php -r '$B = new Blitz(); $B->load("AAA");'
Warning: blitz::load(): SYNTAX ERROR: end with no begin (noname_loaded_from_zval: line 1, pos 19) in Command line code on line 1

**Comment by alexeyrybak** [comment]
This is a bug added with a pull for complex expressions, expression parser gets crazy on simple constructions like " " (for this simple expressions parser makes 10 parse_arg calls):

*** FUNCTION *** blitz_parse_call, started at pos=1, c=I
text:  IF a
METHOD: IF, pos=3, c= , type=2
*** FUNCTION *** blitz_parse_arg: 97
*** FUNCTION *** blitz_parse_arg: 45
*** FUNCTION *** blitz_parse_arg: 62
*** FUNCTION *** blitz_parse_arg: 60
*** FUNCTION *** blitz_parse_arg: 33
*** FUNCTION *** blitz_parse_arg: 45
*** FUNCTION *** blitz_parse_arg: 69
*** FUNCTION *** blitz_parse_arg: 45
*** FUNCTION *** blitz_parse_arg: 62
*** FUNCTION *** blitz_parse_arg: 0
IF expression: missing operand at the begin of stack, mismatch?
parsed lexem: IF

**Comment by poison** [comment]
Ok, On it!

**Comment by poison** [comment]
Should be fixed in PR #18

**Comment by poison** [comment]
Possibly there's an error with IF's if the object is NULL, need to look into it as well. Will keep you posted

**Comment by poison** [comment]
I think I got it covered now in PR #18 (76052cd3b610fd6d2ac3ef6f65ac1a0c46c7d1f6)
