### ISSUE TITLE
{{ date("Y") }} does not seem to work

### ISSUE THREAD

**Issue by wouterds** [alexeyrybak/blitz#33]
Hi,

As far as I know you can execute native PHP functions with Blitz, right?
But for some reason `{{ date("Y") }}` just prints "Y". Known bug? What are the alternatives?

Cheers,
Wouter

**Comment by alexeyrybak** [comment]
please use php::date('Y')
$T = new Blitz();
$T->load('{{ php::date("Y"); }}');
$T->display();

I will keep this issue open as I think it's because of old legacy built-in blitz functions that should be better removed now.

**Comment by WouterDS** [comment]
Thanks!

**Comment by alexat** [comment]
It also may be viable to make plain {{ xxx() }} callbacks to use just source Blitz object methods and not call PHP functions as a fallback, enforcing {{ php::xxx() }} syntax to make code more clean/predictable.
