### ISSUE TITLE
Differences between now and PHP7 versions

### ISSUE THREAD

**Issue by quentincurtet** [alexeyrybak/blitz#45]
Hi,

In terms of use and installation, what will be the differences between the actual version and the PHP7 one ?

Thanks for your answers.

Cordially.

**Comment by alexeyrybak** [comment]
Why are you asking? there are no changes in the installation process, as for the PHP7 branch - you can see from the branch graph that all new updates go into the PHP7 branch now, but we don't have many changes. So, as for now - no major changes.
