### ISSUE TITLE
Segfault when variable is too long

### ISSUE THREAD

**Issue by poison** [alexeyrybak/blitz#47]
When a variable is a path and it's too long, this results in a segfault

<?php
include('common.inc');

$tpl = <<<TPL
{{a.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGH}}
TPL;

$data = array(
    'a' => array(
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGH' => 'No crash'
    )
);

$t = new Blitz();
$t->load($tpl);
$t->display($data);

?>

**Comment by akademic** [comment]
![](http://static.deathandtaxesmag.com/uploads/2011/04/Why-Jackie.jpg)
