### ISSUE TITLE
Expressions in external functions

### ISSUE THREAD

**Issue by ksimka** [alexeyrybak/blitz#50]
In #22 expressions inside `if` feature was implemented. What about external functions?

Now 

```
{{my_custom_func(var == "foo")}}
```

ends with `SYNTAX ERROR: invalid method call`.

(v 0.10.2 if it matters)

**Comment by alexeyrybak** [comment]
current expressions support is very trivial, if/unless only

**Comment by ksimka** [comment]
Any plans on this? I can put two 🍻  for this feature.

**Comment by alexeyrybak** [comment]
what about putting lines of code for this feature? seriously - no plans yet

**Comment by alexeyrybak** [comment]
no plans to extend the expression support
