### ISSUE TITLE
Mac OS X Capitan (x64) Error on make

### ISSUE THREAD

**Issue by arthurkushman** [alexeyrybak/blitz#51]
/bin/sh /Users/arthur/www/test_tmpl/blitz-master/libtool --mode=compile cc  -I. -I/Users/arthur/www/test_tmpl/blitz-master -DPHP_ATOM_INC -I/Users/arthur/www/test_tmpl/blitz-master/include -I/Users/arthur/www/test_tmpl/blitz-master/main -I/Users/arthur/www/test_tmpl/blitz-master -I/usr/local/Cellar/php70/7.0.12_5/include/php -I/usr/local/Cellar/php70/7.0.12_5/include/php/main -I/usr/local/Cellar/php70/7.0.12_5/include/php/TSRM -I/usr/local/Cellar/php70/7.0.12_5/include/php/Zend -I/usr/local/Cellar/php70/7.0.12_5/include/php/ext -I/usr/local/Cellar/php70/7.0.12_5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /Users/arthur/www/test_tmpl/blitz-master/blitz.c -o blitz.lo
mkdir .libs
 cc -I. -I/Users/arthur/www/test_tmpl/blitz-master -DPHP_ATOM_INC -I/Users/arthur/www/test_tmpl/blitz-master/include -I/Users/arthur/www/test_tmpl/blitz-master/main -I/Users/arthur/www/test_tmpl/blitz-master -I/usr/local/Cellar/php70/7.0.12_5/include/php -I/usr/local/Cellar/php70/7.0.12_5/include/php/main -I/usr/local/Cellar/php70/7.0.12_5/include/php/TSRM -I/usr/local/Cellar/php70/7.0.12_5/include/php/Zend -I/usr/local/Cellar/php70/7.0.12_5/include/php/ext -I/usr/local/Cellar/php70/7.0.12_5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/arthur/www/test_tmpl/blitz-master/blitz.c  -fno-common -DPIC -o .libs/blitz.o
/Users/arthur/www/test_tmpl/blitz-master/blitz.c:45:10: fatal error: 'ext/standard/php_smart_str.h' file not found
#include "ext/standard/php_smart_str.h"
         ^
1 error generated.
make: *** [blitz.lo] Error 1

**Comment by alexeyrybak** [comment]
Please make sure you proceed with all the configure steps properly (./configure --with-php-config=/usr/local/bin/correct-php-config-binary) and  provide your php version / which branch do you use. Pretty sure it's a configurational issue.

**Comment by alexeyrybak** [comment]
I think you have several PHP versions installed and you just try to compile the PHP7 branch with PHP5 libraries for example.

**Comment by alexeyrybak** [comment]
Any update on this?

**Comment by arthurkushman** [comment]
Google is good at helping people, thx.
