### ISSUE TITLE
How to traverse an array of indexes?

### ISSUE THREAD

**Issue by johnw2018** [alexeyrybak/blitz#58]
How to traverse an array of indexes

如何遍历索引数组

**Comment by alexeyrybak** [comment]
Please explain in more details what problem you are solving.

**Comment by NickyX3** [comment]
Алексей, мне кажется, что johnw2018 имел ввиду проход по "плоскому массиву"
типа
$data['names'] = ['Nic','Alexey'];
И было бы удобно не создавать под это двумерный массив с массивами типа
$data['names'] = [['name'=>'Nic'],['name'=>'Alexey']];
А иметь внутри блока некую переменную, например $_value, которая бы и содержала элемент списка (с конвертацией в скаляр string как вариант, или в такую $_value попадали бы ТОЛЬКО скаляры, что еще удобнее)
И был бы подобный шаблон
{{ BEGIN names }}
{{ $_value }},
{{ END }}
Вместо
{{ BEGIN names }}
{{ $name }},
{{ END }}

**Comment by alexeyrybak** [comment]
Sounds like additional magic. Internal representation of a list is numerical list (array) of hashes, not scalars. Very straightforward and easy to understand/debug.

**Comment by alexeyrybak** [comment]
will not fix, no details were given
